In [12]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline


torch.randint(1,9,(2,2))
torch.randperm(10)
a = torch.randn(1000)
b = torch.histogram(a,10)
b[0]

tensor([  6.,  37.,  93., 162., 218., 222., 160.,  70.,  23.,   9.])

In [14]:
torch.full((5,5),1.8)

tensor([[1.8000, 1.8000, 1.8000, 1.8000, 1.8000],
        [1.8000, 1.8000, 1.8000, 1.8000, 1.8000],
        [1.8000, 1.8000, 1.8000, 1.8000, 1.8000],
        [1.8000, 1.8000, 1.8000, 1.8000, 1.8000],
        [1.8000, 1.8000, 1.8000, 1.8000, 1.8000]])

In [ ]:
t = torch.randn(2,3,4) # blocks,rows,columns,chanells. 
t

tensor([[[-1.1676, -0.3431, -1.4590,  0.0700],
         [ 0.2077,  0.5903, -0.3509, -0.4590],
         [-0.2752, -1.0913, -1.0899,  0.9409]],

        [[ 1.0014, -0.1657, -0.0807, -1.3620],
         [-0.1968,  0.0362, -0.1298, -0.0812],
         [-0.0478,  0.6048, -1.6956,  0.6388]]])